### ISSUE TITLE
Website doesn't resolve

### ISSUE THREAD

**Issue by leandropls** [formencode/formencode#100]
$ host www.formencode.org
    Host www.formencode.org not found: 3(NXDOMAIN)
    $ host formencode.org
    Host formencode.org not found: 3(NXDOMAIN)

**Comment by lambacck** [comment]
Thanks for letting me know. I'm looking into it.

**Comment by hlwsmith** [comment]
They've been getting much picky with registrant email being funtional. Make sure the email listed in the whois for the Registrant Email record works as they actually verify them these days. (ie. you'll likely need to respond to an email sent there.)

**Comment by lambacck** [comment]
Yeah well we're basically at the mercy of @ianb noticing that I've been trying to contact him about it. The domain never got transferred to me so I have not control over it.
