### ISSUE TITLE
http://www.formencode.org exemples

### ISSUE THREAD

**Issue by muffatruffa** [formencode/formencode#107]
I think there's  some misleading error in the class
`class SecurePassword(validators.FancyValidator)`
The regex
`letter_regex = re.compile(r'[a-zA-Z]')`
should be
`letter_regex = re.compile(r'[^a-zA-Z]')`
and later in the code to raise the exception
`raise Invalid.....omitted`
should be
`raise formencode.Invalid`

**Comment by drnlm** [comment]
Since the example is using re.sub to remove all letters, the regexp is correct as far as I can see.

Changing the raise to match the other examples seems a worthwhile improvement.
