### ISSUE TITLE
1.3.0 cannot provide a universal wheel

### ISSUE THREAD

**Issue by sigmavirus24** [formencode/formencode#117]
When FormEncode is installed with semi-modern versions of pip, pip will first build a wheel and then cache it. Because the project has [`universal = 1` in the wheel section of your setup.cfg](https://github.com/formencode/formencode/blob/1.3.0/setup.cfg#L29), pip will cache the wheel and indicate that the built wheel is suitable for py2 and py3. The problem is that the project uses 2to3 to ensure that FormEncode is correct for the version of Python it installs on. So if you run your tests against Python 2 first, then FormEncode will fail on Python 3.

Could a patch version of 1.3.0 be released with `universal = 0`? This means pip will cache two separate wheels, one for py2 and one for py3.

**Comment by phdru** [comment]
It also causes problems in the other direction. I pip-installed FormEncode for Python 3.4 and then for Python 2.7. Got a bug in 2.7 with `class Declarative(object, metaclass=DeclarativeMeta)`.

**Comment by lambacck** [comment]
1.3.1 released also 2.0.0a1 both of which fix the universal wheel problem.

**Comment by phdru** [comment]
Thanks, that really helps! sqlobject/sqlobject@12790bba :+1:

**Comment by sigmavirus24** [comment]
Thank you @lambacck!
