### ISSUE TITLE
`AttributeError: StringIO instance has no attribute 'encoding'` when running tests

### ISSUE THREAD

**Issue by AvivC** [formencode/formencode#121]
Hello :)

When I run the tests for the project using `python setup.py nosetests` (on Python 2.7 and Windows 7), 9 tests fail with the following error:

    AttributeError: StringIO instance has no attribute 'encoding'

How can I fix this? Thank you

**Comment by Cito** [comment]
It works for me - which tests are failing? Make sure you have the latest version of nose and pycountry installed. Also `set LANGUAGE=C` before running the tests. Run `python setup.py develop` before running `nosetests` or use `python setup.py nosetests`.

**Comment by AvivC** [comment]
Thank you for the reply. What does the `LANGUAGE` environment variable mean?

**Comment by Cito** [comment]
The environment variable `LANGUAGE` which defines the used locale. Otherwise some validators may return translated strings with non-ascii encodings. The tests assume the default C locale, i.e. untranslated english text in ascii encoding.
