### ISSUE TITLE
Requesting formencode on anaconda

### ISSUE THREAD

**Issue by umarbrowser** [formencode/formencode#136]
Hi, 
if you have time please update formencode to lattest version on conda because only the old version is there and its require for my project, and if you don't have time to package it your self you can give me permission i can do it and continue to maintain it for new updates.
thankyou

**Comment by umarbrowser** [comment]
@ianb please response?

**Comment by lambacck** [comment]
What do I need to do to give you permission?

**Comment by lambacck** [comment]
I don’t see an existing anaconda package so you should be able to [upload it yourself](. If committing something to this repo makes that easier then I’ll gladly review a PR.

**Comment by lambacck** [comment]
Sorry, I accidentally hit close while trying to paste the anaconda package instruction URL: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by umarbrowser** [comment]
Ok thanks ones again, I will start right away.

**Comment by umarbrowser** [comment]
HI @lambacck there was a repository on conda-forge with the same formencode name here are what my pull request says https://github.com/conda-forge/staged-recipes/pull/5708#issuecomment-383562282

and here are the repo: https://github.com/conda-forge/formencode-feedstock
