### ISSUE TITLE
Formencode Email validator does not recognize emails with name

### ISSUE THREAD

**Issue by NucleaPeon** [formencode/formencode#139]
Lots of email programs use the format

    "User Name <user@email.com>"

formencode.validators.Email fails to validate this format.

```
>>> Email.to_python("asdf@asdf.asdf")
'asdf@asdf.asdf'
>>> Email.to_python("My Name <asdf@asdf.asdf>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/bigleaf/lib/python3.4/site-packages/formencode/api.py", line 479, in to_python
    vp(value, state)
  File "/home/vagrant/bigleaf/lib/python3.4/site-packages/formencode/validators.py", line 1354, in _validate_python
    value, state)
formencode.api.Invalid: The username portion of the email address is invalid (the portion before the @: My Name <asdf)
```

**Comment by NucleaPeon** [comment]
Additional info: https://askleo.com/why_are_email_addresses_sometimes_in_anglebrackets/

**Comment by jvanasco** [comment]
That's not an email address, that's a particular way of displaying an email address along with a chosen display name. 

Many programs and usage patterns would break if the validator suddenly allowed that type of address in, and further processing would be needed to separate out the display name and actual email address.

You can build a custom validator that allows an address like that in.

**Comment by NucleaPeon** [comment]
I was hoping there'd be a built in solution, but you make perfect sense. I've built my own custom validator to solve the issue, thanks.
