### ISSUE TITLE
License change or not?

### ISSUE THREAD

**Issue by ondrejj** [formencode/formencode#152]
According to changelog, formencode license has been changed to MIT. But there are still "License: PSF" strings in PKG-INFO and setup.py. Please fix and release again. Thank you. Here is what grep founds:

```
$ fgrep -r PSF
PKG-INFO:License: PSF
FormEncode.egg-info/PKG-INFO:License: PSF
setup.py:      license='PSF',
```

I am trying to build formencode for EPEL-8 (CentOS/RHEL 8), but not sure if I can use this mixed licensed package. :-(

**Comment by drnlm** [comment]
Was this not addressed by https://github.com/formencode/formencode/issues/115 ? AFAICS, the PSF license is only mentioned in the CONTRIBUTORS file in the current code.
