### ISSUE TITLE
Document: "state" is a MultiDict ?

### ISSUE THREAD

**Issue by mckea** [formencode/formencode#165]
It seems that the "state" variable must be a multidict, but I don't see this documented anywhere.

Do I have this wrong or should the documentation be updated?

**Comment by lambacck** [comment]
State is an object not any kind of of dict. Formencode itself only performs attribute access on state. The primary attributes it looks for to be passed from outside is `state._`. Formencode adds other attributes itself to state (for instance Schema [adds the attributes](https://github.com/formencode/formencode/blob/master/formencode/schema.py) `key` and `full_dict` to help with nesting but only if a non-None). Where are you seeing the need for state to be a multidict?

**Comment by mckea** [comment]
Using a dict for state failed.  I noticed in existing code that a MultiDict had been used.  

Subclassing dict and added a '_' attribute works.

**Comment by lambacck** [comment]
State is explicitly documented as being an object and the documentation also defines what attributes are accessed/used: http://www.formencode.org/en/latest/Validator.html#state

**Comment by lambacck** [comment]
You can see an example State object and usage as part of pyramid_simpleform: https://github.com/Pylons/pyramid_simpleform/blob/673cc105fca7b1bbe8a119ee33897fc4574e4593/pyramid_simpleform/__init__.py#L14

**Comment by mckea** [comment]
Thanks
