### ISSUE TITLE
license file path

### ISSUE THREAD

**Issue by stanislavlevin** [formencode/formencode#166]
With https://github.com/formencode/formencode/pull/158
the license file is going to be installed into `/usr/LICENSE.txt` which violates FHS.

https://docs.python.org/3/distutils/setupscript.html#installing-additional-files:
> The directory should be a relative path. It is interpreted relative to the installation prefix (Python’s sys.prefix for system installations; site.USER_BASE for user installations).

Probably, `data_files` is not the best for this.

Context: distribution of `formencode` on LInux distro(RPM build):
`/usr/bin/python3 setup.py install --skip-build --root=/usr/src/tmp/python3-module-FormEncode-buildroot --force`

**Comment by retorquere** [comment]
Same problem here, the setup tries to write into /usr/local/LICENSE.txt

**Comment by lambacck** [comment]
The wheel build in #174 should do the right thing. docs are not include, license is in egg-info.
