### ISSUE TITLE
Only one read the docs admin

### ISSUE THREAD

**Issue by lambacck** [formencode/formencode#169]
@Cito I don't have admin access to read the docs. We need to fix the webhook to trigger doc builds and we should have more than one admin in case something happens to someone. Can you please add me. I've also sent you an email.

**Comment by Cito** [comment]
Sure, I've added you now. You can also consider using GitHub pages for the documentation, like described [here](https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/) for example.

Btw, thanks for keeping FormEncode alive. I'm not using it any more, so I haven't contributed in the last years.
