### ISSUE TITLE
[i18n] How to use multiple domains?

### ISSUE THREAD

**Issue by Kilte** [formencode/formencode#76]
I have the following schema:

```python
import datetime

from formencode import Schema
from formencode.validators import DateConverter, TimeConverter

_ = lambda x: x


class DateTimeSchema(Schema):
    messages = {'invalid_date': _('Invalid date')}
    date = DateConverter(month_style='dd/mm/yyyy')
    time = TimeConverter(use_datetime=True)

    def to_python(self, value, state=None):
        value = super(DateTimeSchema, self).to_python(value, state)
        try:
            value = datetime.datetime.combine(value['date'], value['time'])
        except TypeError:
            raise Invalid(self.message('invalid_date', state), value, state)
        return value
```

I can't translate `invalid_date` message immediately because user locale is not defined at this time.
So I use `lambda x: x` to make message visible for extractor.

 `state._` can translate messages using only one domain. Right?
How to use custom domain for each schema/validator?

I could use lazy translator, but it is impossible, because FormEncode can't override `__doc__` attribute (message must be a string). And it will translate already translated strings.

**Comment by lambacck** [comment]
I'm not sure that you are using this with but this is what I do with Pyramid and pyramidsimpleform (paraphrased from a more complicated system since this code sits behind another function):

```py
from pyramid_simpleform import Form, State
from pyramid.i18n import get_localizer, TranslationString, TranslationStringFactory

fe_tsf = TranslationStringFactory('FormEncode')
def some_view(request):
	def formencode_translator(x):
		if not isinstance(x, TranslationString):
			x = fe_tsf(x)
		return get_localizer(request).translate(x)

	form = Form(request, state=State(_=formencode_translator, request=request))
```

In this case the domain is bundled with the TranslationString instance. This allows multiple domains to be handled. So FormEncode strings come as regular unicode strings and we build a TranslationString from it with the right domain. While custom validators can have a local domain.

**Comment by Kilte** [comment]
I have a `validate()` decorator:
```python
from some_framework import request


class validate(object):
    def __init__(self, schema):
        self.translator = Translator(domain='FormEncode')
        self.schema = schema
    def __call__(self, action):
        def wrapper(*args, **kwargs):
            self.schema.to_python(reques.params, self.translator.state)
            return action(*args, **kwargs)
```
It is only example, in original decorator i can use a list of validators and do other things.

If i need to use another domain, i must to specify it for each schema and validator. As for me, it's not nice solution.

See this: https://github.com/formencode/formencode/blob/master/formencode/schema.py#L136
After `to_python(value, state)` is invoked, `state` will be passed to all `pre_validators`.
How to use another domain for some field of the schema? 
Remeber, we shouldn't do it in a validator, when i need to set domain for all validators in a package.

So far, I see the following solution:
```python
from UserString import UserString

class LazyString(UserString, basestring):
        def __init__(self, translator, s):
                self.__data = unicode(s)
                self.translator = translator
        @property
        def data(self):
                return self.translator(self.__data)
        @data.setter
        def data(self, value):
                self.__data = value
        def __unicode__(self):
                return unicode(self.data)

_ = lambda x: u'{} translation'.format(x)
s = LazyString(_, 'some string')
```

But it not works because [`_initialize_docstring()`](https://github.com/formencode/formencode/blob/master/formencode/api.py#L307) method expects that message is a string.
And i have the following error:
```
in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```
Workaround:
```python
Validator._initialize_doctstring = classmethod(lambda cls: None)
```
It's not nice, but works. In this case I don't need to specify a translator for each schema/validator. Just create a LazyTanslator: `_ = lambda x: LazyString(real_translator, x)` and be happy :)

**Comment by lambacck** [comment]
I think you are over thinking this. Just use translationstring: https://pypi.python.org/pypi/translationstring

The function I provided above will do exactly what you want. Where you have custom messages, use a TranslationStringFactory as your _ function:

```py
from translationstring import TranslationStringFactory
from formencode import Schema
from formencode.validators import DateConverter, TimeConverter

_ = TranslationStringFactory('mydomain')


class DateTimeSchema(Schema):
    messages = {'invalid_date': _('Invalid date')}
    date = DateConverter(month_style='dd/mm/yyyy')
    time = TimeConverter(use_datetime=True)

    def to_python(self, value, state=None):
        value = super(DateTimeSchema, self).to_python(value, state)
        try:
            value = datetime.datetime.combine(value['date'], value['time'])
        except TypeError:
            raise Invalid(self.message('invalid_date', state), value, state)
        return value

```

Then an expanded version of my example above:
```py

class State(object):
       def __init__(self, _):
           self._ = _

fe_tsf = TranslationStringFactory('FormEncode')
def validate(request, schema):
    def formencode_translator(x):
        if not isinstance(x, TranslationString):
            x = fe_tsf(x)
        return dgettext(x.domain, x)

    state=State(_=formencode_translator)
    values = schema.to_python(request.params, state)
    do_something(values)

```

The point here is that TranslationString is a thin wrapper around a normal string that add the domain for translation as a property of the string and your state._ function can have logic that looks for the existence of domain on the string and act appropriately to perform the translation.

**Comment by Kilte** [comment]
That's I need! Thank you.
