### ISSUE TITLE
Feature Request - ability to disable htmlfill for tags

### ISSUE THREAD

**Issue by jvanasco** [formencode/formencode#80]
Using htmlfill on form errors is great, but it can be rather limiting in that it can only handle a single form on a given page by default.  If there are multiple forms on a page (such as login & register), all elements on both forms are processed with the defaults from the error.  The only existing workaround for this is to generate forms separately, and then pipe them into a template as partials.  Depending on an applications workflow, this might not be easily accomplished.  we found it's much easier to just put prefixes on all the "logical" forms, so there is no overlap.  It's an annoying apporach though.

A novel approach that looks like it might work, would be to use tag attributes to control how htmlfill works with more granularity.

• render a tag with a prefix to disable formencode from rewriting that tag:

```
<input type="text" name="foo" value="bar" data-htmlfill-ignore="true" />
<input type="text" name="foo" value="bar" data-formencode-ignore="1" />
<input type="text" name="foo" value="bar" data-formencode="ignore" />
```

• render a tag with an attribute that declares a form "set", used  to group forms together.  if a "form_set" or "form_name" is passed into `htmlfill.render`, only form elements with a matching tag will be rendered

```
<input type="text" name="foo" value="bar" data-formencode-form="form_a" />
<input type="text" name="foo" value="bar" data-formencode-set="form_a" />
```

**Comment by lambacck** [comment]
Mako and Jinja both have features where you can pipe a subset of the page through a function. (I discussed this with you on the mailing list previously)[https://sourceforge.net/p/formencode/mailman/message/29532202/]. Can you please elaborate on how what you are asking for is better than that? Maybe some fleshed out example of how this would simplify your code?

As an update to what I stated in that previous message, I'm pretty sure that: 
```html
<%block filter="formfillfn">
    Some form content
</%block>
```
 is equivalent Mako syntax to the ```{% filter formfillfn %}``` syntax provided by Jinja.

**Comment by lambacck** [comment]
All that said, I don't personally use htmlfill so I'm not particularly inclined to write features for it. If someone else wants to write features for htmlfill and existing code is not broken then I'd be willing to accept a pull request.

**Comment by jvanasco** [comment]
So we've been using approaches like that.  They often become a bit of a hassle though, because we have to maintain an extended bit of logic.  Often times - like with login/register dialogs - we actually have a simple HTML file.

This was more of an "what if..." type of question than a "would you please?"

Since you're open to pull-requests, I'll send one over shortly.  I got this working in a few lines of code -- i screwed up the github commit though, so need to re-integrate off a newer version.
